PERIPHERALS = pit
DRIVERS = pacer usb_serial adxl345 panic nrf24
SRC = hat.c adxl345_PWM.c radio_module.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
